apiVersion: serving.yatai.ai/v1alpha2
kind: BentoDeployment
metadata:
  name: inference-graph-demo
  namespace: yatai
spec:
  bento_tag: inference_graph:yau4ohhnugmvpuqj
  ingress:
    enabled: true
  resources:
    limits:
        cpu: 500m
        memory: "1Gi"
    requests:
        cpu: 1000m
        memory: "1Gi"
  autoscaling:
    max_replicas: 5
    min_replicas: 1
  runners:
  - name: bert-base-uncased
    resources:
      limits:
        cpu: 2000m
        memory: "4Gi"
      requests:
        cpu: 1000m
        memory: "2Gi"
    autoscaling:
      max_replicas: 4
      min_replicas: 1
  - name: distilbert-base-uncased-finetuned-sst-2-english
    resources:
      limits:
        cpu: 2000m
        memory: "4Gi"
      requests:
        cpu: 1000m
        memory: "2Gi"
    autoscaling:
      max_replicas: 4
      min_replicas: 1
  - name: prosusai-finbert
    resources:
      limits:
        cpu: 2000m
        memory: "4Gi"
      requests:
        cpu: 1000m
        memory: "2Gi"
    autoscaling:
      max_replicas: 4
      min_replicas: 1
